### ISSUE TITLE
Investigate into using itertools

### ISSUE THREAD

**Issue by pickfire** [connorskees/grass#15]
Itertools provide `MultiPeek`, a peekable iterator but I don't think they have cursors or the sort. The good thing is that it provides a lot of good stuff like `peeking_take_while`. The downside is I don't see an alternative for `truncate_iterator_to_cursor`.

**Comment by connorskees** [comment]
The `truncate_iterator_to_cursor` function was implemented specifically for use in `grass`. Without that functionality it would be much more tedious to implement `url(...)` and `min(...)/max(..)` parsing.

It would be difficult to justify bringing in the entirety of itertools for functionality that we are not currently using. In general I would prefer to keep our dependencies as small as possible. 

Thank you for the idea; however, for now it seems best to stick with `peekmore`.
