### ISSUE TITLE
docs.rs failed to build grass-0.3.0

### ISSUE THREAD

**Issue by MartinKavik** [connorskees/grass#2]
- https://docs.rs/crate/grass/0.3.0
- https://docs.rs/crate/grass/0.3.0/builds/226208
- https://crates.io/crates/grass/  (missing link `Documentation`)

**Comment by connorskees** [comment]
Thanks for pointing this out!

This actually seems to be due to a regression in the rust compiler. I've made an issue on the rust repo, and I think for now there just might not be docs unless there's a way to configure that they be built with the stable compiler.

**Comment by connorskees** [comment]
I figured out a temporary workaround for this bug, one can now find the docs here, https://docs.rs/grass/0.3.2/grass/
