### ISSUE TITLE
Investigate into measureme

### ISSUE THREAD

**Issue by pickfire** [connorskees/grass#21]
We could add self profiling to grass to find out which part of compilation takes the most time. [measureme](https://github.com/rust-lang/measureme) from rust (also used by boa) would be an interesting option.

https://boa-dev.github.io/2020/07/03/boa-release-09.html

**Comment by connorskees** [comment]
This would potentially be useful as a tool that lives in another crate, but I don't want to include such functionality in this crate. Sass does not typically need to be optimized like JavaScript.
