### ISSUE TITLE
Investigate using IndexMap to represent SassMap

### ISSUE THREAD

**Issue by connorskees** [connorskees/grass#3]
Currently, the map type is implemented as a vector of key-value pairs, which means that insertion, lookup, and removal are all O(n). In addition, construction of map literals is O(n^2).

I was initially planning to implement a better structure for the SassMap ad hoc, but it seems like [this structure](https://github.com/bluss/indexmap) would be a good fit instead.

This issue is a reminder as I do not intend on touching this for a while. The performance of maps is not incredibly important for right now.

**Comment by MartinKavik** [comment]
(Note - we use `IndexMap` on multiple places in Seed - and so far no problems with API or functionality.)

**Comment by connorskees** [comment]
I've tried implementing this a few times, but it seems that the complexity in implementation outweighs any performance gain here. Namely, the comparison between values (e.g. `red == #ff0000`) is difficult to represent using hashes. It is uncertain that using `IndexMap` would even improve performance, and benchmarking has shown that maps in general are quite fast despite the poor algorithmic complexity.

For these reasons I am closing this issue.
