### ISSUE TITLE
Unable to overwrite a file

### ISSUE THREAD

**Issue by MidasLamb** [connorskees/grass#34]
Currently, i'm trying to use cargo make with watch to keep recompiling the scss with grass. But after the first time it fails with:
```
Error: Os { code: 9, kind: Other, message: "Bad file descriptor" }
```

The problem seems to be this line:
https://github.com/connorskees/grass/blob/fdf8e6136c86e03ac219777e15f80e5b7520b278/src/main.rs#L194

https://doc.rust-lang.org/std/fs/struct.File.html#method.open

`File::open()` opens the file in read only mode.

**Comment by MidasLamb** [comment]
I'd like to fix this and create a PR for this if that's ok?

**Comment by connorskees** [comment]
Sure! That sounds great :) I'll release the patch as `0.10.2` as soon as it's merged
