### ISSUE TITLE
More flexibility in import resolution

### ISSUE THREAD

**Issue by elkowar** [connorskees/grass#46]
For my usecase, I'm applying some additional preprocessing to the scss source. This works well with the from_string way of loading a file, but it does not allow me to apply the same preprocessing to files that are _imported_ in that main scss file.

My proposed solution would be to add a trait, let's call it `ImportLoader` or whatever, which specifies a single function that takes a filepath and returns the file content as a String. 
This could then be used to both apply arbitrary logic to the paths, thus allowing for more intricate file resolution in different usecases, as well as apply transformations to the file contents itself, as would be my usecase.

If this is something you would consider adding, or if you can think of any other, more fitting solution for my problem, I'd be more than happy to work on a PR for this!

**Comment by undefinedDarkness** [comment]
This would be very handy to have

**Comment by elkowar** [comment]
Alternatively, this could also be a simple `Box<dyn Fn(&'a Path) -> String>` stored in the Options which could be applied to all file load operations. A `FileLoader` trait may allow for more flexibility in the future, although I couldn't think of any more thing that it _could_ do here. Thus the simple Function may be cleaner.

**Comment by cipriancraciun** [comment]
I was just about to submit a similar feature request.  :)

My reason for such a feature is though somewhat different:  currently I'm using the `sass-rs` crate (based on the "original" C library) to compile the CSS as part of the `build.rs` workflow;  thus in onder to have `cargo build` or `cargo run` detect any changes in the dependencies, which now includes the initial SCSS files, I need to know which other files has each SCSS ended-up loading.

Thus I would use such a `ImportLoader` to just record the loaded files.  Therefore I would be nice to have a "default" `ImportLoader` that does the usual stuff, and I could just wrap that.

----

Setting that asside, one could also use such an `ImportLoader` to generate SCSS source code that is hard or cumbersome to achieve with plain SCSS.  (For example in one of my experiments I wanted to generate some combinations like `{component}x{modifier}x{submodifier}`;  the SCSS code looks quite strange...)  :)

**Comment by connorskees** [comment]
I really like this idea! This has been partially implemented in a fork [here](https://github.com/chris-morgan/grass), and I am waiting for the author to submit a PR. 

It is possible this feature will be a breaking API change, but I'd like to avoid that if possible.

**Comment by jdanyow** [comment]
This would be especially handy in scenarios like the following where we're importing an npm package. We're currently using parcel to build scss which uses node's module resolution algorithm but would switch to grass asap once we can replicate node module resolution via this new flexibility feature.

https://github.com/microsoft/atlas-design/blob/e9c3ca98b4d5f9b23ac8fd9afcc1c9fb246b2fa2/css/src/core/index.scss#L1-L2
