### ISSUE TITLE
compressed output is eliding zeros

### ISSUE THREAD

**Issue by ryanbarry** [connorskees/grass#53]
**Minimal Reproducible Example**:
```
.box {
    box-shadow: 0 0.5em gray;
}
```

**`grass` Output**:
(with style set to `compressed`)
```
.box{box-shadow: .5em gray}
```

**`dart-sass` Output**:
(with style set to `compressed`)
```
.box{box-shadow:0 .5em gray}
```

the output _does_ match dart-sass when they both have style set to `expanded`

**Comment by connorskees** [comment]
Hello, thank for this report. This has been resolved in https://github.com/connorskees/grass/commit/a6eb1fb88a5cdf0be6ebf3aa50fc3247ed63df6c. This fix will be released in `0.10.8` later today, or tomorrow.

**Comment by ryanbarry** [comment]
awesome, such quick turnaround! also, grass is great, thanks for putting it together!

**Comment by connorskees** [comment]
This has been published to crates.io as `v0.10.8`. Thanks again for such a nice report!
