### ISSUE TITLE
Working WASM version for Browsers/Deno

### ISSUE THREAD

**Issue by hironichu** [connorskees/grass#54]
Hello,

Today as I was looking for a way to compile Sass in my project, I was annoyed to not being able to use any npm module with Deno because of some breaking changes, so I decided to use Grass and compile it into wasm to use the WebAssembly module, turns out after many tries it worked, 

I had to do some edit to the lib.rs file in order to compile it without error, but I am sure it's not breaking changes.

I just learned Rust only today, so my code might be just garbage! But if it can help, I just wanted to share this.

Here's a link to the Deno module https://github.com/hironichu/denosass (The updated Grass rust source code is not in there yet)

> Edit : This module also runs in browsers, should work in nodejs as well but have not tried.

**Comment by connorskees** [comment]
Hello,

Thank you for using this library. I'm going to close out this issue to clean up the issue tracker. If you want to discuss your use case further, you may want to check out the [discussions tab](https://github.com/connorskees/grass/discussions/categories/show-and-tell).
