### ISSUE TITLE
Try using beef

### ISSUE THREAD

**Issue by pickfire** [connorskees/grass#6]
https://github.com/maciejhirsz/beef is faster than `Cow` in standard library.

**Comment by pickfire** [comment]
I tried a bit but I got some errors. `the trait bound `std::string::String: std::convert::From<beef::generic::Cow<'_, str, beef::lean::internal::Lean>>` is not satisfied`, the weird thing is that beef already implements `From<String>`.

**Comment by connorskees** [comment]
Thank you for bringing this up! When I initially changed `Value::to_css_string` and `Value::inspect` to return `Cow`s, I did so very loosely, and we actually were receiving very little benefit from it. I've written a pull request to use `beef` and make better use of `Cow`.
