### ISSUE TITLE
Expose SassErrorKind as public

### ISSUE THREAD

**Issue by elkowar** [connorskees/grass#62]
In my project (https://github.com/elkowar/eww), I already have a error reporting infrastructure and error rendering system which defines how errors for non-scss stuff looks. It'd be very nice if I could integrate grass errors into that code.

For this, the `SassErrorKind` field of `SassError` and the Type itself would need to be public. That way, I could access the Location and Span information of the error myself, and decide how to render the errors, rather than being restricted to the built-in rendering solution from grass.

**Comment by connorskees** [comment]
This is a reasonable ask. I've exposed a public enum `grass::ErrorKind` and a public method `grass::Error::kind` for accessing this type. This change has been published to crates.io in `0.11.2`.
