### ISSUE TITLE
add support to include_sass macro to autocompile sass files and include it in the binaries 

### ISSUE THREAD

**Issue by prabirshrestha** [connorskees/grass#63]
Most of the template engines doesn't support css/sass files. Would be great if there was `include_sass_str!("./style.sass")` and `include_sass_bytes!("./sytle.sass")` so that we can easily embed the compiled version of the file without creating a `build.rs` file. 

Looking to something similar to this https://crates.io/crates/include-flate.

**Comment by connorskees** [comment]
Hello,

Thank you for this suggestion. This has been implemented in https://github.com/connorskees/grass/commit/8095c2345eaf139362a0c3826e2f688aeb7b3166 and should release to crates.io in a bug fix version bump at some point in the near future.
