### ISSUE TITLE
npm package is out-dated

### ISSUE THREAD

**Issue by guoyunhe** [connorskees/grass#65]
I saw the npm version is 0.10.0 published two years ago. Can you publish the latest version for npm?

**Comment by jdanyow** [comment]
I think this would accelerate adoption by making it really easy to migrate from node-sass and sass.
https://npmtrends.com/grass-vs-node-sass-vs-sass

**Comment by connorskees** [comment]
Thank you for raising this issue. [`grass` 0.12.0](https://www.npmjs.com/package/@connorskees/grass) has been published to npm. Going forward, new releases of grass will again be mirrored on npm.

**Comment by JiangWeixian** [comment]
Thanks awesome work, it's able to replace sass-loader?

**Comment by connorskees** [comment]
@JiangWeixian The library published to NPM would not be able to as far as I'm aware. Is there a reason you want to replace `sass-loader`?

**Comment by JiangWeixian** [comment]
@connorskees looks like much fast than node-sass(or others)

**Comment by guoyunhe** [comment]
@connorskees I checked out the NPM package and found an issue. The package.json has:

```json
{
  "module": "grass.js",
}
```

But this will cause "cannot find module" problems (Node.js by default look for index.js first if you don't sepcify `main` field in package.json). It should be:

```json
{
  "type": "module",
  "main": "grass.js",
}
```

**Comment by JiangWeixian** [comment]
@guoyunhe use `exports` field will be much better.

**Comment by connorskees** [comment]
Yes, the environment that the NPM package is currently built for is the browser. The use case for the NPM package is primarily to power https://connorskees.github.io/grassmeister which is a Sass repl similar to [Sassmeister](https://www.sassmeister.com/), but with a more up-to-date Sass compiler.

I haven't targeted node as I assume grass can't really beat dart-sass by too much there. Last time I checked the performance of grass compiled to WASM, it was much slower than native and more or less the same speed as dart-sass. Though, this was probably 2 or 3 years ago so perhaps things have gotten better since then.

I think I'll remove the reference to the WASM package in the readme.

**Comment by Atulin** [comment]
> Going forward, new releases of grass will again be mirrored on npm.

![image](https://github.com/user-attachments/assets/382b9763-4636-4129-8be0-e94e2b79d283)
![image](https://github.com/user-attachments/assets/820543db-696a-48fa-b7c7-d6c8cf7f72eb)

I take it something changed in that regard?

**Comment by connorskees** [comment]
what's your use case for the version published to npm? are there missing features in the version on npm that you would want?

**Comment by Atulin** [comment]
My use case is using it in a build script I have that uses dart-sass right now. There are no missing features per see (maybe besides the documentation being nonexistent), I just wanted to look into Grass as a potential replacement and a two-year outdated package is a hard sell.

**Comment by connorskees** [comment]
oh, what's wrong with the native build for that case?

**Comment by connorskees** [comment]
(the cli for which is installable with `cargo install`)

**Comment by Atulin** [comment]
The necessity of installing the entire Rust toolchain

**Comment by connorskees** [comment]
why is that bad or cumbersome in a build script?

**Comment by Atulin** [comment]
It's yet another thing to install, and for the sole purpose of adding a dependency. If the project was using Rust in any other capability, sure, but I'd rather not make it a requirement for everybody who needs to build the SASS code to install Rust on their machine.
