### ISSUE TITLE
Comments in --var not removed

### ISSUE THREAD

**Issue by eugenesvk** [connorskees/grass#75]
upd: I see that it's a common sass misfeature https://github.com/sass/sass/issues/2770
so unlikely to expect grass to deviate

I'm using grass via zola SSG and I've noticed that comments in `--var` are not stripped from the output, thus breaking my ability to add comments with explanations for colors
```
// file.sass
:root.light
  --var:  	oklch(.87 0   90)	// comment not removed in the output
```

I see that `CSS variables should include everything, notably comments https://github.com/connorskees/grass/pull/67` on https://github.com/connorskees/grass/issues/19, which is maybe related and implies this is intentional, but I don't understand the reason behind that, the comments like these aren't meant to be included
Although that example has `foo: //;` a semicolon, while the one I'm using is the cleaner sass version, so maybe this explains it?

(although some online dart sass tools strip the comments properly fro this format)

**Comment by connorskees** [comment]
I've thought about a flag like "libsass quirks mode" that makes parsing more similar to libsass, but I wouldn't want to deal with the added maintenance burden of this. I would be hesitant to add a general flag for grass-specific parsing changes for similar reasons, in addition to compatibility concerns with other Sass implementations.

**Comment by eugenesvk** [comment]
Found a trick to use proper comments in the output, `#{interpolation}` in the property name disables this quirk and uses regular Sass parsing behavior

https://github.com/sass/sass/issues/2586#issuecomment-438050730
```sass
:root.light
  #{--var}:	oklch(.87 0   90)	// comment are removed in the output!!!
```
