### ISSUE TITLE
`cargo doc` only works with nightly

### ISSUE THREAD

**Issue by simon-bourne** [connorskees/grass#81]
Hi, when I run `cargo doc` on a crate that depends on `grass` 0.12.4 with stable Rust 1.70.0, I get the error:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> xxx/grass_compiler-0.12.4/src/lib.rs:35:18
   |
35 | #![cfg_attr(doc, feature(doc_cfg))]
   |                  ^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not document `grass_compiler`
```

**Comment by connorskees** [comment]
Thanks for mentioning this -- I was actually thinking about whether I should fix this last week.

This should be resolved in https://github.com/connorskees/grass/commit/346b8c127b37098237bdea8254d78edc47ac45c4, which will release to crates.io at some point soon. Leaving this issue open until this change has been published, but feel free to close before then.

**Comment by connorskees** [comment]
This change has been released to crates.io as version [`0.13.0`](https://crates.io/crates/grass/0.13.0). Thanks again for the bug report!

**Comment by simon-bourne** [comment]
Works great, thanks!
