### ISSUE TITLE
Using grass as a sass parser without the transformation

### ISSUE THREAD

**Issue by bradzacher** [connorskees/grass#82]
I'm working on some tooling to do dependency analysis of my company's sass files.
In a nutshell I want to parse a sass file, extract the "imports" (eg `@use`, `@include`, etc) and build a dependency graph across our rather large codebase.

I was looking into the `grass_compiler` internals (correct me if I'm wrong) but it looks like most of the infra required to parse and traverse a sass file is `pub(crate)` - making it unusable externally.

I saw https://github.com/connorskees/grass/issues/77 mentions

> AST traversal can be built through the internals crate [grass_compiler](https://crates.io/crates/grass_compiler).

Does this mean that you want to support this sort of usecase for 1.0?

**Comment by connorskees** [comment]
GitHub seems to be having trouble with my comment, as the tab keeps crashing from OOM while I'm trying to reply.

As you mention, the AST internals necessary for doing traversal are not currently exposed. So far no one has asked for such functionality, and I haven't been able to decide on an API I like.

I was interested in the problem you described, and made a small attempt at it. I wrote some code using grass that traverses the AST of a large Sass library and ouputs a dotviz file of the dependency graph. You can find this sample here https://gist.github.com/connorskees/7af84cfe4b3157e0120dad06f33cd112. It's quite hacky and I really don't like the API, but it does function correctly.

I made public all of the necessary internals in https://github.com/connorskees/grass/commit/8b34d0ee2af7a2a8688178e088c7e4aeea7d6db4. I'm not sure when this will release to crates.io, but in the meantime you should be able to access this commit by cloning the repo locally and using a path dependency. 

Please let me know if there's anything more you would need to implement what you have described.

**Comment by connorskees** [comment]
[Sample visualization of the output from the gist above](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0D%0A%20%20node%20%5Bshape%3Drecord%20fontname%3DArial%5D%3B%0D%0A%0D%0A%20%20%22themes%2F_default.scss%22%20-%3E%20%7B%20%22themes%2Fdefault%2F_styles.scss%22%2C%20%22themes%2Fdefault%2F_schemes.scss%22%20%7D%0D%0A%20%20%22themes%2Fdefault%2F_light.scss%22%20-%3E%20%7B%20%22utils%2F_functions.scss%22%2C%20%22_settings.scss%22%2C%20%22colors%2F_index.scss%22%2C%20%22utils%2F_box-shadow.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22layout%2F_grid.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22content%2F_miscs.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22forms%2F_input-range.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22themes%2Fdefault%2F_styles.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%2C%20%22utils%2F_functions.scss%22%2C%20%22colors%2F_index.scss%22%20%7D%0D%0A%20%20%22components%2F_accordion.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22forms%2F_input-file.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22components%2F_loading.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22components%2F_modal.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22components%2F_tooltip.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22layout%2F_landmarks.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22content%2F_embedded.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22_index.scss%22%20-%3E%20%7B%20%22layout%2F_scroller.scss%22%2C%20%22forms%2F_input-file.scss%22%2C%20%22utils%2F_copyright.scss%22%2C%20%22components%2F_tooltip.scss%22%2C%20%22content%2F_table.scss%22%2C%20%22components%2F_dropdown.scss%22%2C%20%22utilities%2F_reduce-motion.scss%22%2C%20%22forms%2F_input-search.scss%22%2C%20%22content%2F_typography.scss%22%2C%20%22content%2F_button.scss%22%2C%20%22components%2F_card.scss%22%2C%20%22components%2F_loading.scss%22%2C%20%22forms%2F_checkbox-radio-switch.scss%22%2C%20%22components%2F_nav.scss%22%2C%20%22forms%2F_input-color.scss%22%2C%20%22layout%2F_grid.scss%22%2C%20%22forms%2F_input-date.scss%22%2C%20%22components%2F_modal.scss%22%2C%20%22components%2F_progress.scss%22%2C%20%22content%2F_embedded.scss%22%2C%20%22layout%2F_document.scss%22%2C%20%22content%2F_link.scss%22%2C%20%22components%2F_accordion.scss%22%2C%20%22content%2F_code.scss%22%2C%20%22utilities%2F_accessibility.scss%22%2C%20%22components%2F_group.scss%22%2C%20%22_settings.scss%22%2C%20%22layout%2F_container.scss%22%2C%20%22themes%2F_default.scss%22%2C%20%22content%2F_miscs.scss%22%2C%20%22layout%2F_section.scss%22%2C%20%22layout%2F_landmarks.scss%22%2C%20%22forms%2F_input-range.scss%22%2C%20%22forms%2F_basics.scss%22%20%7D%0D%0A%20%20%22pico.scss%22%20-%3E%20%7B%20%22_index.scss%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22components%2F_nav.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22forms%2F_input-date.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22forms%2F_input-color.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22utilities%2F_reduce-motion.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22forms%2F_checkbox-radio-switch.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22content%2F_typography.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22themes%2Fdefault%2F_schemes.scss%22%20-%3E%20%7B%20%22themes%2Fdefault%2F_dark.scss%22%2C%20%22sass%3Amap%22%2C%20%22_settings.scss%22%2C%20%22themes%2Fdefault%2F_light.scss%22%20%7D%0D%0A%20%20%22layout%2F_scroller.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22forms%2F_basics.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22content%2F_code.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22components%2F_group.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22layout%2F_container.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22content%2F_link.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22components%2F_progress.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22components%2F_dropdown.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22content%2F_table.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22themes%2Fdefault%2F_dark.scss%22%20-%3E%20%7B%20%22utils%2F_functions.scss%22%2C%20%22colors%2F_index.scss%22%2C%20%22_settings.scss%22%2C%20%22utils%2F_box-shadow.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22layout%2F_document.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22utilities%2F_accessibility.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22layout%2F_section.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22forms%2F_input-search.scss%22%20-%3E%20%7B%20%22_settings.scss%22%2C%20%22sass%3Amap%22%20%7D%0D%0A%20%20%22components%2F_card.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22content%2F_button.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%2C%20%22_settings.scss%22%20%7D%0D%0A%20%20%22_settings.scss%22%20-%3E%20%7B%20%22sass%3Amap%22%20%7D%0D%0A%7D%0D%0A)

**Comment by connorskees** [comment]
The changes described in my previous comment have been released to crates.io as version [`0.13.0`](https://crates.io/crates/grass_compiler/0.13.0). I will note that there have been some changes to the AST field names that will require updating in the code sample I posted.

If there is additional functionality you are interested in using `grass` for, please do open another issue.
