### ISSUE TITLE
`map.has-key` doesn't support `$keys..`. argument

### ISSUE THREAD

**Issue by yokomizor** [connorskees/grass#94]
Hey there,

Since version 0.13, `map.get` supports `$keys...` argument as per: #80, #83.

It would be cool to have the same for `map.has-key`.

I am willing to submit a patch, but I wonder if someone already familiar with the code base could just copy/paste from #80, and call it a day.

Thank you for the crate

**Comment by connorskees** [comment]
Hi,

Thanks for opening this issue. I've added support for the `$keys...` argument to `map.has-key` in https://github.com/connorskees/grass/commit/f16fc40bdefd10d6ebe5c1c77e4c12616e8f1486, which should be released to crates.io sometime soon

**Comment by connorskees** [comment]
This change has been released to crates.io in version [`0.13.4`](https://crates.io/crates/grass/0.13.4)
