### ISSUE TITLE
`string.split` missing but present in dart-sass 1.57.0

### ISSUE THREAD

**Issue by xpe** [connorskees/grass#95]
grass doesn't yet support `string.split`, which has been available in dart-sass since 1.57.0.

https://sass-lang.com/documentation/modules/string/#split

> `string.split($string, $separator, $limit: null) //=> list`
>
> Compatibility:
> * Dart Sass since 1.57.0
> * LibSass: ✗
> * Ruby Sass: ✗
>
> Returns a bracketed, comma-separated list of substrings of `$string` that are separated by `$separator`. The `$separator`s aren’t included in these substrings.
>
> If `$limit` is a number 1 or higher, this splits on at most that many `$separator`s (and so returns at most `$limit + 1` strings). The last substring contains the rest of the string, including any remaining `$separator`s.

**Comment by connorskees** [comment]
closed by #96
